{
    "name": "HR Contract",
    'version': '16.0.1.0.0',
    "summary": "HR Contract",
    "category": "HR",
    "author": "Dev Team",
    "license": "",
    "installable": True,
    "maintainers": ["Dev"],
    "depends": [
        "hr_contract",
        # "hr_payroll_community",
    ],
    "data": [
        "data/monitoring_contract_sch.xml",
        'data/mail_template_data.xml',
        "sequence/sequence.xml",
        # "views/hr_contract_views.xml",
        "views/res_config_settings_views.xml",
        "views/hr_employee_views.xml",
        "report/report_views.xml",
        "report/kompensasi_report.xml",
        "report/contract_report.xml",
    ],
    "sequence": 1,
    "license": "AGPL-3",
}
